# Generated by Django 5.2.1 on 2025-05-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Суперадмин'), ('admin', 'Админ'), ('storekeeper', 'Кладовщик')], default='storekeeper', max_length=20),
        ),
    ]
