# Generated by Django 5.2.1 on 2025-05-18 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Веб-сайт')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('recipient', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('dispatched', 'Отгружено'), ('pending', 'Ожидается'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.SlugField(help_text='Уникальный идентификатор (например, A1-B2)', unique=True)),
                ('type', models.CharField(choices=[('zone', 'Зона'), ('section', 'Секция'), ('shelf', 'Полка'), ('cell', 'Ячейка')], default='zone', max_length=10, verbose_name='Тип места')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость, кг/м³')),
                ('temperature', models.CharField(blank=True, max_length=20, null=True, verbose_name='Температурный режим')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.place', verbose_name='Родительское место')),
            ],
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('received', 'Получено'), ('pending', 'Ожидается'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'unique_together': {('product',)},
            },
        ),
    ]
