# Generated by Django 5.2.1 on 2025-05-16 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.SlugField(help_text='Уникальный идентификатор (например, A1-B2)', unique=True)),
                ('type', models.CharField(choices=[('zone', 'Зона'), ('section', 'Секция'), ('shelf', 'Полка'), ('cell', 'Ячейка')], default='zone', max_length=10, verbose_name='Тип места')),
                ('capacity', models.IntegerField(default=0, verbose_name='Вместимость, кг/м³')),
                ('temperature', models.CharField(blank=True, max_length=20, null=True, verbose_name='Температурный режим')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.place', verbose_name='Родительское место')),
            ],
        ),
    ]
