# Generated by Django 5.2.1 on 2025-05-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('store', '0002_remove_supplier_contact_info_supplier_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('recipient', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('dispatched', 'Отгружено'), ('pending', 'Ожидается'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'unique_together': {('product',)},
            },
        ),
    ]
