# Generated by Django 5.2.1 on 2025-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('report_type', models.CharField(choices=[('current_stock', 'Текущие остатки'), ('low_stock', 'Низкие остатки'), ('operations', 'Складские операции'), ('product_history', 'История товара')], max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
            ],
        ),
    ]
