# Generated by Django 5.2.1 on 2025-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('шт', 'Штуки'), ('кг', 'Килограммы'), ('л', 'Лиры'), ('уп', 'Упаковки'), ('м', 'Метры')], max_length=10),
        ),
    ]
